version: '3'
services:
  fastapi:
    build:
      context: .
    container_name: fastapi_app
    env_file:
      - ./env/.env.redis
      - ./env/.env.elastic
      - ./env/.env.settings
    environment:
      REDIS_HOST: redis  # название сервиса redis
      ELASTIC_HOST: http://elastic

      PROJECT_NAME: movies
    networks:
      - sprint_4_net
    depends_on:
      elastic:
        condition: service_healthy
    restart: unless-stopped

  elastic:
    image: elasticsearch:8.6.2
    container_name: elasticsearch-8.6.2
    environment:
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    networks:
      - sprint_4_net
    expose:
      - 9200
    restart: unless-stopped
    healthcheck:
      test: curl -u elastic:elastic -s -f elastic:9200/_cat/health >/dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 50

  redis:
    image: redis:7.0-alpine
    container_name: redis-7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    expose:
      - 6379
    command: redis-server --appendonly yes
    volumes: 
      - redis_data:/data
    networks:
      - sprint_4_net

  nginx:
    image: nginx:1.23.4-alpine
    container_name: nginx-1.23.4-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - sprint_4_net
    ports:
      - "80:80"
    depends_on:
      - fastapi
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  sprint_4_net:
    name: sprint_4_net
